# Generated by Django 4.0 on 2021-12-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='maps',
            field=models.TextField(),
        ),
    ]
